apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-vault
  namespace: catalyst-os
  labels:
    app: catalyst-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalyst-vault
  template:
    metadata:
      labels:
        app: catalyst-vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.15.2
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: "0.0.0.0:8200"
          args:
            - "server"
            - "-dev"
---
apiVersion: v1
kind: Service
metadata:
  name: catalyst-vault-service
  namespace: catalyst-os
spec:
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: catalyst-vault
