apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: catalyst-os

resources:
  - 01-namespace.yaml
  - 02-configmap-secrets.yaml
  - 03-postgres-pgvector.yaml
  - 04-vault.yaml
  - 05-fastapi-service.yaml
  - 06-node-gateway.yaml
  - 07-frontend.yaml
  - 08-ingress.yaml
